filingNav<script>
import $ from 'jquery';
import moment from 'moment';
import Gumshoe from 'gumshoejs'
import SmoothScroll from 'smooth-scroll';
import 'bootstrap';
import 'bootstrap4-toggle';
import { toRaw } from 'vue';

import { countyCodeFromCounty, devLog, handlePrintMacro, initAfterVue, getError, toCountyCode } from '../utils';

function detectChangesInChromeStorage(app) {
  chrome.storage.onChanged.addListener(function (changes, namespace) {
    var countsChange = changes['counts'];
    var responsesChange = changes['responses'];

    if (countsChange === undefined && responsesChange === undefined) return;
    if (countsChange.newValue === undefined) {
      app.clearAll();
      return;
    }
    app.loadAll(function () { });
  });
}

export default {
  // el: '#filing-app',
  data() {
    return {
      settings: {
        attorney: '',
        attorneyAddress: '',
        attorneyPhone: '',
        footer1: '- Generated by ExpungeVT -',
        footer2: '- A Code for BTV Project -',
        customNote: '',
        role: 'AttyConsult',
        forVla: true,
        emailConsent: true,
        affidavitRequired: false,
        groupCounts: false,
        groupNoas: false,
      },
      saved: {
        defName: '',
        defAddress: [''],
        defDOB: '',
        counts: [],
        defEmail: '',
      },
      responses: {},
      fees: {},
      fines: {},
      countiesContact: {},
      popupHeadline: '',
      roleCoverLetterText: {},
      coverLetterContent: {},
      stipDef: {},
    };
  },
  watch: {
    // Affects "consolidation" checkboxes in filings page header
    // This watch ensures that "NoAs" checkbox IS checked when "Petitions" checkbox is checked
    groupCounts: {
      handler(value) {
        if (value) {
          this.settings.groupNoas = true;
        }
      },
    },
    // Affects "consolidation" checkboxes in filings page header
    // This watch ensures that "Petitions" checkbox IS NOT checked when unchecking "NoAs" checkbox
    groupNoas: {
      handler(value) {
        if (!value) {
          this.settings.groupCounts = false;
        }
      },
    },
    responses: {
      handler() {
        this.saveResponses();
      },
      deep: true,
    },
    settings: {
      handler() {
        this.saveSettings();
        //this.$nextTick(function () {
          //vanilla js
        //});
      },
      deep: true,
    },
    saved: {
      handler() {
        devLog(
          'counts updated - line:' + getError()
        );
        this.saveCounts();
        //this.$nextTick(function () {
          //call any vanilla js functions after update.
          //initAfterFilingRefresh();
        //});
      },
      deep: true,
    },
  },
  beforeCreate() {
    $.getJSON(
      'https://raw.githubusercontent.com/codeforbtv/expungeVT-admin/master/config/adminConfig.json',
      function (data) {
          console.log(this);
        this.countiesContact = data['countyContacts'];
        this.popupHeadline = data['expungeHeadline'];
        this.roleCoverLetterText = data['roleText'];
        this.coverLetterContent = data['letter'];
        this.stipDef = data['stipDefinition'];
        devLog(
          'adminConfig data has been set at line: ' + getError()
        );
        devLog(data);
      }
    );
  },
  mounted() {
    devLog('App mounted!');
    this.loadAll();
    detectChangesInChromeStorage(this);
    handlePrintMacro(this);
    //This is to make sure dynamically created table are unique across tab in order to avoid errors
    this.uniqueId = this._uid;
  },
  methods: {
    saveSettings: function () {
      // devLog("save settings", this.settings)
      settingString = JSON.stringify(this.settings);
      localStorage.setItem('localExpungeVTSettings', settingString);
    },
    saveResponses: function () {
      devLog(
        'save responses' + getError()
      );
      chrome.storage.local.set({
        responses: this.responses,
      });
    },
    saveCounts: function () {
      devLog('saving counts');
      chrome.storage.local.set({
        counts: toRaw(this.saved),
      });
    },
    loadAll: function (callback) {
      var self = this;
      if (callback === undefined) {
        callback = function () { };
      }
      devLog(localStorage.getItem('localExpungeVTSettings'));
      localResult = JSON.parse(localStorage.getItem('localExpungeVTSettings'));
      if (
        localResult !== undefined &&
        localResult !== '' &&
        localResult !== null
      ) {
        devLog('settings found');
        this.settings = localResult;
        devLog(this.settings);
      } else {
        devLog('No settings found, saving default settings');
        this.saveSettings();
      }

      chrome.storage.local.get(function (result) {
        //test if we have any data
        devLog('loading all');
        devLog(JSON.stringify(result));
        if (result.counts !== undefined) {
          devLog(result.counts);
          self.saved = result.counts;
        }

        if (result.responses !== undefined) {
          self.responses = result.responses;
        }

        callback();
        //this.$nextTick(function () {
          //call any vanilla js functions that need to run after vue is all done setting up.
          //initAfterVue();
        //});
        setTimeout(() => {
          initAfterVue();
        }, 0);
      });
    },
    newCount: function (event) {
      this.saved.counts.push({ description: 'New', filingType: '' });
    },
    confirmDeleteCount: function (event, countId) {
      event.stopPropagation();
      if (this.saved.counts.length > 1) {
        var currentCount = this.saved.counts.filter(
          (count) => count.uid === countId
        )[0];
        if (
          confirm(
            `Are you sure that you would like to delete the count \"${currentCount.description}\"?`
          )
        ) {
          this.deleteCount(countId);
        }
        return;
      }
      if (
        confirm(
          'Are you sure that you would like to delete the last count, this will clear all petitioner information.'
        )
      ) {
        this.clearAll();
      }
    },
    deleteCount: function (countId) {
      index = this.saved.counts.findIndex((x) => x.uid === countId);
      Vue.delete(this.saved.counts, index);
    },
    clearAll: function () {
      chrome.storage.local.remove(['counts', 'responses'], function () {
        document.location.reload();
      });
    },
    nl2br: function (rawStr) {
      var breakTag = '<br>';
      return (rawStr + '').replace(
        /([^>\r\n]?)(\r\n|\n\r|\r|\n)/g,
        '$1' + breakTag + '$2'
      );
    },
    printDocument: function () {
      window.print();
    },
    saveHtml: function () {
      let dataPojo = {
        saved: this.saved,
        responses: this.responses,
      };
      saveAllCountsToHtml(JSON.stringify(dataPojo));
    },
    returnCountyContact: function (cty) {
      allCounties = this.countiesContact;
      devLog('Number: ' + allCounties[cty]);
      return allCounties[cty];
    },
    proSeFromRole: function (preparerRole) {
      if (preparerRole == 'AttyAppear') {
        return false;
      } else {
        return true;
      }
    },
    checkDocketMatch: function (longDocket, shortDocket, county) {
      if (!longDocket) return false;
      let concatDocket = shortDocket + ' ' + countyCodeFromCounty(county);

      if (concatDocket !== longDocket) {
        return false;
      } else {
        return true;
      }
    },
    getFeeWaiverStatusFromFiling: function (filingId) {
      docket =
        'NoA-' + filingId.substring(filingId.indexOf('-') + 1) + '-feeForm';
      return this.responses[docket];
    },
    numOfFeeWaiversInGroup: function (filings) {
      return filings.filter((f) => f.type == 'feeWaiver').length;
    },
    getNextNotaryDate: function () {
      let currentDate = moment();
      let janThisYear = moment(currentDate.format('YYYY') + '-01-31');

      if (currentDate.isBefore(janThisYear) && isOdd(currentDate)) {
        return janThisYear.format('MMMM DD, YYYY');
      } else if (!isOdd(currentDate)) {
        return moment(janThisYear).add(1, 'years').format('MMMM DD, YYYY');
      } else if (currentDate.isAfter(janThisYear) && isOdd(currentDate)) {
        return moment(janThisYear).add(2, 'years').format('MMMM DD, YYYY');
      }
      function isOdd(num) {
        let numInt = parseInt(num.format('YYYY'));
        return numInt % 2;
      }
    },
    notarizableFilings: function (filings) {
      let affidavitCount = 0;
      filings.forEach((county) => {
        county.filings.forEach((filing) => {
          if (filing.type === 'feeWaiverAffidavit') {
            affidavitCount++;
          }
        });
      });
      if (affidavitCount > 0) {
        return true;
      } else {
        return false;
      }
    },
    stringAgeInYearsAtDate: function (date, dob) {
      if (!date) return '';
      if (!dob) return '';
      let fromTime = moment(date).diff(moment(dob));
      let duration = moment.duration(fromTime);
      return (duration.asDays() / 365.25).toFixed(0) + ' yo';
    },
    sinceNow: function (value) {
      if (!value) return '';

      let fromTime = moment(value).diff(moment(), 'milliseconds');
      let duration = moment.duration(fromTime);
      let years = duration.years() / -1;
      let months = duration.months() / -1;
      let days = duration.days() / -1;
      if (years > 0) {
        var Ys = years == 1 ? years + 'y ' : years + 'y ';
        var Ms = months == 1 ? months + 'm ' : months + 'm ';
        return Ys + Ms;
      } else {
        if (months > 0) return months == 1 ? months + 'm ' : months + 'm ';
        else return days == 1 ? days + 'd ' : days + 'd ';
      }
    },
    dateFormatSimple: function (value) {
      if (!value) return '';
      return moment(value).format('MM/DD/YYYY');
    },
    toCountyCode,
  },
  computed: {
    petitioner: function () {
      return {
        name: this.saved.defName,
        dob: this.saved.defDOB,
        address: this.nl2br(this.saved.defAddress),
        email: this.saved.defEmail,
      };
    },
    /* Checks the computed `filings` property to see how many unique dockets there are */
    numDockets: function () {
      const dockets = this.filings
        .map((f) =>
          f.filings
            .map((f2) => f2.docketNums.map((d) => d.string).flat())
            .flat()
        )
        .flat();
      const uniqueDockets = dockets.reduce((acc, n) => {
        if (!acc.includes(n)) {
          acc.push(n);
        }
        return acc;
      }, []);
      return uniqueDockets.length;
    },
    todayDate: function () {
      date = moment().format('MMMM D[, ]YYYY');
      return date;
    },
  },
}
</script>

<template>
  <div>
    <div v-if="petitioner.name" class="header-bar-wrapper no-print">
        <div class="header-bar">
          <h1>Counts for {{petitioner.name}}</h1>
          <div class="header-bar__controls">
            <button v-on:click="newCount" class="btn btn-primary">
              Add Count <i class="fas fa-plus-circle"></i>
            </button>

            <a href="filings.html" class="btn btn-success">
              View Petitions <i class="fas fa-external-link-alt"></i>
            </a>
          </div>
        </div>
      </div>

      <div style="margin: 40px;">
        <h2>Petitioner Information</h2>

        <div>
          <label>
            Name
            <input class="form-control" v-model="saved.defName" />
          </label>
          <label class="pet-label">
            Date of Birth
            <input class="form-control" type="date" v-model="saved.defDOB" />
          </label>
        </div>

        <div>
          <label class="pet-label">
            Address
            <textarea
              class="form-control"
              v-model="saved.defAddress"
              placeholder="e.g. 123 Main Street"
            ></textarea>
          </label>
        </div>
      </div>

      <section
        class="edit-count"
        v-for="(group, index) in saved.counts"
        v-bind:id="group"
        style="margin: 40px;"
      >
        <h3 class="edit-count__title">
          Count {{index + 1}}:
          <span v-if="group.description">{{group.description}}</span>
        </h3>
        <p><b>{{group.docketNum}} {{toCountyCode(group.county)}}</b></p>

        <form>
          <div>
            <label style="min-width: 70%;">
              Count Description<b>*</b>
              <input
                required=""
                class="form-control"
                v-model="group.description"
                placeholder="Description"
              />
            </label>

            <div>
              <label>
                <span>Docket Number<b>*</b></span>
                <input
                  required=""
                  class="form-control"
                  v-model="group.docketNum"
                  placeholder="Docket Num"
                />
              </label>
              <label>
                <span>County<b>*</b></span>
                <select required="" class="form-control" v-model="group.county">
                  <option>Addison</option>
                  <option>Bennington</option>
                  <option>Caledonia</option>
                  <option>Chittenden</option>
                  <option>Essex</option>
                  <option>Franklin</option>
                  <option>Grand Isle</option>
                  <option>Lamoille</option>
                  <option>Orange</option>
                  <option>Orleans</option>
                  <option>Rutland</option>
                  <option>Washington</option>
                  <option>Windham</option>
                  <option>Windsor</option>
                </select>
              </label>

              <label>
                <span>Disposition Date<b>*</b></span>
                <input
                  required=""
                  class="form-control"
                  type="date"
                  v-model="group.dispositionDate"
                  placeholder="Disposition Date"
              /></label>
            </div>

            <label>
              Filing for this count<b>*</b>
              <select
                class="form-control petitionSelect selectpicker"
                v-model="group.filingType"
              >
                <option value="X">No Filing</option>
                <option value="ExC">Expunge Conviction</option>
                <option value="ExNC">Expunge Non-Conviction</option>
                <option value="ExNCrim">Expunge Non-Criminal</option>
                <option value="SC">Seal Conviction</option>
                <option value="SDui">Seal DUI</option>
                <option value="StipExC">(Stipulated) Expunge Conviction</option>
                <option value="StipExNC"
                  >(Stipulated) Expunge Non-Conviction</option
                >
                <option value="StipExNCrim"
                  >(Stipulated) Expunge Non-Criminal</option
                >
                <option value="StipSC">(Stipulated) Seal Conviction</option>
                <option value="StipSDui">(Stipulated) Seal DUI</option>
              </select>
            </label>
          </div>

          <hr />

          <div>
            <label>
                <p
                  v-if="!checkDocketMatch(group.docketSheetNum, group.docketNum, group.county) && (group.docketNum || group.county)"
                  class="alert alert-warning"
                >
                  <b>WARNING - Unexpected format: the petition page may not render correctly.</b><br>
                  Expecting "docket <i>sheet</i> number" below to match docket number above followed by the county code: <b><span>{{group.docketNum}} <span v-if="group.county">{{toCountyCode(group.county)}}</span><span v-else>[No County Entered]</span></span></b>
                </p>
              <span>Original Docket Sheet Number</span>
              <input
                class="form-control"
                v-model="group.docketSheetNum"
                placeholder="Docket Num"
              />
            </label>

            <div>
              <label>
                <span>Alleged Offense Date</span>
                <input
                  class="form-control"
                  type="date"
                  v-model="group.allegedOffenseDate"
                  placeholder="Offense Date"
                />
              </label>

              <label>
                <span>Arrest Citation Date</span>
                <input
                  class="form-control"
                  type="date"
                  v-model="group.arrestCitationDate"
                  placeholder="Arrest Citation Date"
                />
              </label>
            </div>

            <div>
              <label width="400px"
                >Offense Disposition
                <input
                  class="form-control"
                  v-model="group.offenseDisposition"
                  placeholder="e.g. Dismissed By State"
                />
              </label>

              <label class="checkbox-inline">
                <input v-model="group.isDismissed" type="checkbox" /><span>
                  Is Dismissed</span
                >
              </label>
            </div>
          </div>

          <hr />

          <div>
            <label for="vsc-title">
              <span>Statue Title</span>
              <input
                id="vsc-title"
                class="form-control"
                v-model="group.titleNum"
                placeholder="Title"
              />
            </label>

            <label for="vsc-section">
              <span>Statute Section</span
              ><input
                id="vsc-section"
                class="form-control"
                v-model="group.sectionNum"
                placeholder="Section"
              />
            </label>

            <label>
              <span>Offense Class</span>
              <select class="form-control" v-model="group.offenseClass">
                <option value="mis">Misdemeanor</option>
                <option value="fel">Felony</option>
              </select>
            </label>
          </div>

          <p v-if="group.titleNum || group.sectionNum || group.offenseClass">
            <b
              >{{group.titleNum || '-'}} V.S.A. &sect; {{group.sectionNum ||
              '-'}} ({{group.offenseClass || '-'}})</b
            >
          </p>

          <div />

          <div>
            <button
              v-on:click="confirmDeleteCount($event,group.uid)"
              class="btn btn-danger"
            >
              Delete Count
            </button>
          </div>
        </form>
      </section>
  </div>
</template>