import { defineStore } from 'pinia'

export const useDataStore = defineStore('data', {
    state: () => {return {
        settings: {
            attorney: '',
            attorneyAddress: '',
            attorneyPhone: '',
            footer1: '- Generated by ExpungeVT -',
            footer2: '- A Code for BTV Project -',
            customNote: '',
            role: 'AttyConsult',
            forVla: true,
            emailConsent: true,
            affidavitRequired: false,
            groupCounts: false,
            groupNoas: false,
            termsChecked: false,
        },
        saved: {
            defName: '',
            defAddress: [''],
            defDOB: '',
            counts: [],
            defEmail: '',
        },
        responses: {},
        fees: {},
        fines: {},
        countiesContact: {},
        popupHeadline: '',
        roleCoverLetterText: {},
        coverLetterContent: {},
        stipDef: {},
    }}
}
)